#! /usr/bin/env python3

import serial
import sys
import os
import argparse
import regex as re
import time
from datetime import datetime, timezone
from colorama import Fore, Back, Style


class colour_str:
    def __init__(self, s: str):
        self.s = s
        self.codes = []

    def __str__(self) -> str:
        """Applies the stored codes when the object is converted to a string."""
        if not self.codes:
            return self.s

        prefix = "".join(self.codes)
        return f"{prefix}{self.s}{Style.RESET_ALL}"

    def _add_style(self, style_code: str) -> "colour_str":
        """Adds a style code and returns self to allow chaining."""
        self.codes.append(style_code)
        return self

    def red(self) -> "colour_str":
        return self._add_style(Fore.RED)

    def green(self) -> "colour_str":
        return self._add_style(Fore.GREEN)

    def yellow(self) -> "colour_str":
        return self._add_style(Fore.YELLOW)

    def dim(self) -> "colour_str":
        return self._add_style(Style.DIM)

    def bright(self) -> "colour_str":
        return self._add_style(Style.BRIGHT)


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-p",
        "--port",
        type=str,
        default="COM3" if os.name == "nt" else "ACM0",
        help="Specify the serial port to connect to, eg ACM0, USB0, COM3",
    )
    parser.add_argument(
        "-b",
        "--baud",
        type=int,
        default=115200,
        help="Baud rate to set the serial port to",
    )
    parser.add_argument(
        "-l", "--log", action="store_true", help="save serial port data to log file"
    )
    parser.add_argument(
        "-lf",
        "--log-file",
        type=str,
        default="",
        help="filename used to save log files. Will appear as date_time_<filename>.txt",
    )
    parser.add_argument(
        "-ld",
        "--log-directory",
        type=str,
        help="Folder to save logging file. Default is script directory",
        default=os.path.join(os.path.dirname(os.path.realpath(__file__)), "logs"),
    )
    parser.add_argument(
        "-c", "--clear", action="store_true", help="Clear terminal before printing"
    )
    parser.add_argument(
        "-t",
        "--print_time",
        type=str,
        default="off",
        choices=["off", "epoch", "ms", "dt"],
        help="print system time on each log line",
    )
    return parser.parse_args()


def get_serial_prefix():
    if os.name == "nt":
        return ""
    return "/dev/tty"


def clear_terminal():
    # clear screen
    if os.name == "nt":
        os.system("cls")
    os.system("clear")


def escape_ansi(line):
    ansi_escape = re.compile(r"(?:\x1B[@-_]|[\x80-\x9F])[0-?]*[ -/]*[@-~]")
    return ansi_escape.sub("", line)


def run_serial_printing_with_logs(
    serial_port_name,
    baud,
    log_file,
    log_directory,
    print_time,
):
    filename = f"{datetime.now().strftime('%Y.%m.%d_%H.%M.%S')}_{log_file}.txt"
    if not os.path.isdir(log_directory):
        os.mkdir(log_directory)

    logging_file = os.path.join(log_directory, filename)
    print(f"Logging to: {logging_file}")

    with open(logging_file, "a+", buffering=1) as file:
        run_serial_printing(serial_port_name, baud, print_time, file)


def add_time_to_line(print_time):
    now_utc = datetime.now(timezone.utc)
    if "epoch" in print_time:
        return f"{now_utc.timestamp():.3f} "
    elif "ms" in print_time:
        return f"{now_utc.timestamp() * 1000:.0f} "
    elif "dt" in print_time:
        return f"{now_utc.replace(tzinfo=None).isoformat(sep=' ', timespec='milliseconds')} "
    return ""


def serial_loop(ser, print_time, file):
    while True:
        if not (line := ser.readline().decode("utf-8", errors="ignore")):
            continue
        line = f"{add_time_to_line(print_time)}{line}"
        print(line, end="")
        if file:
            file.write(escape_ansi(line))  # strip colours


def wait_with_spinner(serial_port_name, count):
    loading_bars = ["[==    ]", "[  ==  ]", "[    ==]", "[  ==  ]"]
    """Prints a spinning icon to show that the script is waiting."""
    loading_char = loading_bars[count % len(loading_bars)]

    # Construct the status text using your colour_str class
    status_text = str(
        colour_str(f"Waiting for {serial_port_name} {loading_char}").dim()
    )

    # Use carriage return '\r' to print over the same line
    sys.stdout.write(f"\r{status_text}")
    sys.stdout.flush()

    return count + 1


def run_serial_printing(serial_port_name, baud, print_time=None, file=None):
    count = 0
    while True:
        try:
            time.sleep(0.2)
            with serial.Serial(serial_port_name, baud, timeout=0.05) as ser:
                count = 0
                print("\n" + f" ✅ Connected to {serial_port_name} ".center(50, "-"))
                serial_loop(ser, print_time, file)
        except serial.SerialException:
            count = wait_with_spinner(serial_port_name, count)
        except KeyboardInterrupt:
            print(colour_str(f"\nClosed {serial_port_name}.").dim().green())
            sys.exit(0)


def main():
    args = parse_arguments()

    if args.clear:
        clear_terminal()

    print(colour_str(f"{args}").dim())
    serial_port_name = f"{get_serial_prefix()}{args.port}"

    if args.log:
        run_serial_printing_with_logs(
            serial_port_name,
            args.baud,
            args.log_file,
            args.log_directory,
            args.print_time,
        )
    else:
        run_serial_printing(serial_port_name, args.baud, args.print_time)


if __name__ == "__main__":
    main()
